apiVersion: v1
kind: Service
metadata:
  name: hello-app
  namespace: argocd
  annotations:
    networking.gke.io/managed-certificates: "my-managed-cert"
spec:
  type: LoadBalancer
  selector:
    app: hello-app
  ports:
    - name: http
      port: 80
      targetPort: 5000  # Port HTTP (5000) aplikacji Flask
    - name: https
      port: 443
      targetPort: 5000  # Port HTTPS obsługiwany przez LoadBalancer

