apiVersion: v1
kind: Service
metadata:
  name: hello-app-lb
  namespace: argocd  # Ponownie używamy namespace 'argocd'
  annotations:
    networking.gke.io/managed-certificates: "my-managed-cert"
spec:
  type: LoadBalancer
  selector:
    app: hello-app
  ports:
    - port: 80
      targetPort: 5000