apiVersion: v1
kind: Service
metadata:
  name: hello-app
  namespace: argocd
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/app-protocols: '{"https": "HTTP2"}'
    cloud.google.com/load-balancer-type: "External"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 5000  # Port, na którym działa Twoja aplikacja
    - name: https
      port: 443
      targetPort: 5000  # Obsługa HTTPS
  selector:
    app: hello-app
